In [1]:
import numpy as np

## ARRAY OPERATIONS

#### Arithmetic Operations

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [8]:
 arr2 = a1 + a2 
 arr2   
# Both the arrays must contain same number of elements

array([ 7,  9, 11, 13, 15])

In [9]:
a2 -a1

array([5, 5, 5, 5, 5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
a1 // a2

array([0, 0, 0, 0, 0], dtype=int32)

In [14]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625], dtype=int32)


### Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes without using loops.

In [15]:
l = [10,20,30,40]
arr = np.array(l)

In [16]:
# But it is not possible in list in simple way we have to use complex method like loop and all
# possible in array to add plus 10 in each element of array
arr + 10  

array([20, 30, 40, 50])

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = 10

a + b

array([11, 12, 13])

In [18]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow Copy
Shallow copy shares memory with the original array, while deep copy creates a completely independent copy.
Use shallow copy → save memory, read-only ops

Use deep copy → when you will modify data safely

In [30]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
# Deep Copy : - This slicing change does not happen in the actual array
# But happen in list
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a
b = a.copy()

In [33]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operation

In [37]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
B

array([[5, 6],
       [7, 8]])

In [40]:
# Dot Product, one more way below
A @ B 

array([[19, 22],
       [43, 50]])

In [41]:
# Dot Product 
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [42]:
# Transpose Matrix
A.T  

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation
Stacking Array, here we have to use vectors

In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [48]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
# Horizontal Split
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [53]:
# Vertical Split
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]