# Numpy Indexing and Slicing of Vectors

In [3]:
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[8]

19

In [6]:
arr[1:5] #Here we give index num start and end

array([12, 13, 14, 15])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [8]:
arr[5:]

array([16, 17, 18, 19, 20])

In [9]:
arr_slice = arr[3::2] #[Start:Stop:Step]
arr_slice

array([14, 16, 18, 20])

# Numpy Indexing and Slicing of Matrix

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0,4]    #[row,column]

5

In [12]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [13]:
slice2 = arr[2:4,3:]
slice2

array([[14, 15],
       [19, 20]])

In [14]:
slice3 = arr[3:,3:]
slice3

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [16]:
arr[::2, ::2]


array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [18]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

# Boolean Indexing

In [23]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
arr2 = arr[bool_index]
arr2

array([12, 14, 16, 18, 20])

In [26]:
arr1 = arr[arr % 2 == 0]
arr1

array([12, 14, 16, 18, 20])